table 'Customer Lookup'
	lineageTag: 0918f215-1be9-4126-91fc-6da17c32a8ca

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: cf05cc96-6d0e-41a3-a9f9-40e5cec72081
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column Prefix
		dataType: string
		lineageTag: aed76bcc-b822-4985-ad3a-cfd4533d2e8b
		summarizeBy: none
		sourceColumn: Prefix

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 60fea6f4-9031-41c0-98e4-80d46d307447
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: 1212107b-0217-465d-924e-dda5cd5ddc8b
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column BirthDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 29490d1c-14b2-4d41-af20-74e1a9223e9f
		summarizeBy: none
		sourceColumn: BirthDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MaritalStatus
		dataType: string
		lineageTag: 7d7e70f0-da51-4692-889b-5c0326054654
		summarizeBy: none
		sourceColumn: MaritalStatus

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: c0e38315-de88-4b11-86ae-801a39f671c6
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column EmailAddress
		dataType: string
		lineageTag: 680d07cf-4d8a-4ed4-a8bd-1b526087f67a
		summarizeBy: none
		sourceColumn: EmailAddress

		annotation SummarizationSetBy = Automatic

	column AnnualIncome
		dataType: int64
		formatString: 0
		lineageTag: c70f2ade-26c9-4e1b-971d-fdfe12965092
		summarizeBy: none
		sourceColumn: AnnualIncome

		annotation SummarizationSetBy = Automatic

	column TotalChildren
		dataType: int64
		formatString: 0
		lineageTag: 430b8c33-564c-4b18-a404-d091d92c3848
		summarizeBy: none
		sourceColumn: TotalChildren

		annotation SummarizationSetBy = Automatic

	column EducationLevel
		dataType: string
		lineageTag: 1a76c83b-0e26-4a67-92a7-092e6d37dc4a
		summarizeBy: none
		sourceColumn: EducationLevel

		annotation SummarizationSetBy = Automatic

	column Occupation
		dataType: string
		lineageTag: c6e737fa-7b0a-4210-a9f1-34b9712b5a22
		summarizeBy: none
		sourceColumn: Occupation

		annotation SummarizationSetBy = Automatic

	column HomeOwner
		dataType: string
		lineageTag: 5af5ad19-df6c-4c2b-ad6b-296c744c08d8
		summarizeBy: none
		sourceColumn: HomeOwner

		annotation SummarizationSetBy = Automatic

	column 'Domain Name'
		dataType: string
		lineageTag: 078d7f24-d6ce-4b08-97c6-4b9342bd0ea5
		summarizeBy: none
		sourceColumn: Domain Name

		annotation SummarizationSetBy = Automatic

	column 'Income Level' = IF('Customer Lookup'[AnnualIncome] >= 150000, "Very High", if('Customer Lookup'[AnnualIncome]>=100000, "High",if('Customer Lookup'[AnnualIncome]>=50000,"Average","Low")))
		dataType: string
		lineageTag: 287996a8-4712-4556-8365-b66dabe33f60
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'Education Category' = SWITCH('Customer Lookup'[EducationLevel], "High School","High School","Partial High School","High School", "Bachelors","Undergrad","Partial College","Undergrad", "Graduate Degree","Graduate")
		dataType: string
		lineageTag: a9c20073-51bd-4cd1-82dd-73b96927c575
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'Customer Priority' = ```
			if (
			   'Customer Lookup'[AnnualIncome] >100000 && 'Customer Lookup'[Is Parent?] = "Yes", "Priority", "Standard" 
			) 
			```
		dataType: string
		lineageTag: 4e5336a4-0133-4dae-bc4f-af25ad4bdac6
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'Is Parent?'
		dataType: string
		lineageTag: b4300f92-f32d-4129-8147-bc011bc08d5a
		summarizeBy: none
		sourceColumn: Is Parent?

		annotation SummarizationSetBy = Automatic

	column 'Birth Year' = YEAR('Customer Lookup'[BirthDate])
		dataType: int64
		formatString: 0
		lineageTag: 559953c7-6c1d-4ed1-8b2e-367808da1bb5
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'Full Name'
		dataType: string
		lineageTag: ae3fad21-cc44-4d90-8951-c85d94130fbf
		summarizeBy: none
		sourceColumn: Full Name

		annotation SummarizationSetBy = Automatic

	partition 'Customer Lookup' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Mac\Home\Downloads\Power BI Course Resources\AdventureWorks Raw Data\AdventureWorks Customer Lookup.csv"),[Delimiter=",", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CustomerKey", Int64.Type}, {"Prefix", type text}, {"FirstName", type text}, {"LastName", type text}, {"BirthDate", type date}, {"MaritalStatus", type text}, {"Gender", type text}, {"EmailAddress", type text}, {"AnnualIncome", Int64.Type}, {"TotalChildren", Int64.Type}, {"EducationLevel", type text}, {"Occupation", type text}, {"HomeOwner", type text}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type", {"CustomerKey"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Errors", each [CustomerKey] <> null and [CustomerKey] <> ""),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Filtered Rows", "EmailAddress", "EmailAddress - Copy"),
				    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"EmailAddress - Copy", "Domain Name"}}),
				    #"Extracted Text After Delimiter" = Table.TransformColumns(#"Renamed Columns", {{"Domain Name", each Text.AfterDelimiter(_, "@"), type text}}),
				    #"Extracted Text Before Delimiter" = Table.TransformColumns(#"Extracted Text After Delimiter", {{"Domain Name", each Text.BeforeDelimiter(_, ".com"), type text}}),
				    #"Uppercased Text" = Table.TransformColumns(#"Extracted Text Before Delimiter",{{"Domain Name", Text.Upper, type text}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Uppercased Text", "Is Parent?", each if [TotalChildren] >= 1 then "Yes" else "No"),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Added Conditional Column",{{"Prefix", Text.Proper, type text}, {"FirstName", Text.Proper, type text}, {"LastName", Text.Proper, type text}}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Capitalized Each Word", "Full Name", each Text.Combine({[Prefix], [FirstName], [LastName]}, " "), type text)
				in
				    #"Inserted Merged Column"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

