table 'Price Adjustment(%)'
	lineageTag: 87c081bc-0bc7-4b8f-ace1-d92d2d5d4765

	measure 'Price Adjustment(%) Value' = SELECTEDVALUE('Price Adjustment(%)'[Price Adjustment(%)], 0)
		lineageTag: f201e85d-3fb2-4905-93b1-2550ba5e68f3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Price Adjustment(%)'
		dataType: double
		lineageTag: f84c48ec-7764-4fc2-86cd-994232c0a2f7
		summarizeBy: none
		isDataTypeInferred
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Price Adjustment(%)' = calculated
		mode: import
		source = GENERATESERIES(-1, 1, 0.1)

	annotation PBI_Id = d8f77049594046bda00d9e319d1a6197

