table 'Product Lookup'
	lineageTag: 6daa8209-911a-42ec-8ccc-f5d3045c6149

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 60073ca4-9fef-48b0-93c4-ba48a4dafb68
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductSubcategoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 230ff3ed-0537-4395-bfb3-a0150f6b7cfa
		summarizeBy: none
		sourceColumn: ProductSubcategoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductSKU
		dataType: string
		lineageTag: 4a2cc434-ceb7-4ded-9b06-2089fb469db0
		summarizeBy: none
		sourceColumn: ProductSKU

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 5796d730-8a0d-4d16-91ee-f3251b291a00
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column ModelName
		dataType: string
		lineageTag: e29c3454-f216-4d19-8d71-df3753a48fb8
		summarizeBy: none
		sourceColumn: ModelName

		annotation SummarizationSetBy = Automatic

	column ProductDescription
		dataType: string
		lineageTag: 546e4ed9-7003-4efe-b955-500921dc1504
		summarizeBy: none
		sourceColumn: ProductDescription

		annotation SummarizationSetBy = Automatic

	column ProductColor
		dataType: string
		lineageTag: 48ec5c3d-668d-4dbd-a73c-daa7bfe408d5
		summarizeBy: none
		sourceColumn: ProductColor

		annotation SummarizationSetBy = Automatic

	column ProductSize
		dataType: string
		lineageTag: 6973b8dd-fb0c-46f1-9bd5-c85fe062e4ea
		summarizeBy: none
		sourceColumn: ProductSize

		annotation SummarizationSetBy = Automatic

	column ProductStyle
		dataType: string
		lineageTag: d43533f9-0305-4e03-afd7-5ef569b95910
		summarizeBy: none
		sourceColumn: ProductStyle

		annotation SummarizationSetBy = Automatic

	column ProductCost
		dataType: double
		lineageTag: 857512cd-8fca-4030-8e08-b927fd4e77e2
		summarizeBy: sum
		sourceColumn: ProductCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductPrice
		dataType: double
		lineageTag: e6d6cb31-e2c0-425f-9819-a057387a7657
		summarizeBy: sum
		sourceColumn: ProductPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SKU Type'
		dataType: string
		lineageTag: b458401d-5339-4396-937d-a9b3e81fe9d0
		summarizeBy: none
		sourceColumn: SKU Type

		annotation SummarizationSetBy = Automatic

	column 'SKU Category' = LEFT('Product Lookup'[ProductSKU],SEARCH("-",'Product Lookup'[ProductSKU])-1)
		dataType: string
		lineageTag: 355ac244-fb27-4cdf-a76f-fe457b9dc160
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column Test = ```
			SEARCH("-",'Product Lookup'[ProductSKU]) 
			```
		dataType: int64
		formatString: 0
		lineageTag: b4e7e080-af85-490e-92a6-43eafc5b7b79
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	partition 'Product Lookup' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Mac\Home\Downloads\Power BI Course Resources\AdventureWorks Raw Data\AdventureWorks Product Lookup.csv"),[Delimiter=",", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductKey", Int64.Type}, {"ProductSubcategoryKey", Int64.Type}, {"ProductSKU", type text}, {"ProductName", type text}, {"ModelName", type text}, {"ProductDescription", type text}, {"ProductColor", type text}, {"ProductSize", type text}, {"ProductStyle", type text}, {"ProductCost", type number}, {"ProductPrice", type number}}),
				    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Changed Type", "Text Before Delimiter", each Text.BeforeDelimiter([ProductSKU], "-", 1), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Text Before Delimiter",{{"Text Before Delimiter", "SKU Type"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns","0","NA",Replacer.ReplaceText,{"ProductStyle"})
				in
				    #"Replaced Value"

	annotation PBI_ResultType = Table

