table 'Product Subcategories Lookup'
	lineageTag: cba572ff-e6bc-486d-b39c-6cef431a2482

	column ProductSubcategoryKey
		dataType: int64
		formatString: 0
		lineageTag: de9f68b6-05af-4794-8d71-0ffe326c0fc2
		summarizeBy: none
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column SubcategoryName
		dataType: string
		lineageTag: 1743a205-11e6-4904-8588-4496a8c531d0
		summarizeBy: none
		sourceColumn: SubcategoryName

		annotation SummarizationSetBy = Automatic

	column ProductCategoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 16cefe33-747a-4096-8afe-2b5e6a8618cf
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Product Subcategories Lookup' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Mac\Home\Downloads\Power BI Course Resources\AdventureWorks Raw Data\AdventureWorks Product Subcategories Lookup.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductSubcategoryKey", Int64.Type}, {"SubcategoryName", type text}, {"ProductCategoryKey", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

